### ISSUE TITLE
404 'prismic-toolbar' is not in the npm registry.

### ISSUE THREAD

**Issue by wilbo** [prismicio/prismic-toolbar#1]
after: `npm install prismic-toolbar --save` I get this error:
- 404 'prismic-toolbar' is not in the npm registry.

Is the npm package no longer available?

**Comment by tremby** [comment]
I realize it's over a year later, but it works for me.

**Comment by levimykel** [comment]
We have since removed this from npm and suggest adding the script to your pages like this:
```
<script>
  window.prismic = {
    endpoint: 'https://<your-repo-name>.prismic.io/api/v2'
  };
</script>
<script type="text/javascript" src="//static.cdn.prismic.io/prismic.min.js"></script>
```

Closing this issue.

**Comment by enten** [comment]
@levimykel 
**What is the purpose to do that?** I think it's better for us (developers) to make the choice to update (or not) packages that we use.

Is the repository code updated?

**Comment by tremby** [comment]
@enten, there's an answer to that [here](https://github.com/prismicio/prismic-toolbar/issues/16#issuecomment-396196781)
