### ISSUE TITLE
"new Event" does not work in IE11

### ISSUE THREAD

**Issue by kevinboudot** [prismicio/prismic-toolbar#45]
Hi !

[The Event constructor](https://github.com/prismicio/prismic-toolbar/blob/master/src/messenger.js#L17) does not work in [IE11](https://developer.mozilla.org/en-US/docs/Web/API/Event#Browser_compatibility).

IE11 says :

> Object doesn't support this action

Maybe use a [polyfill](https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work) for IE Only ?

Thank you

**Comment by uglow** [comment]
Can someone (from Prismic) look into this please? We're trying to build a government website which absolutely must support IE11. Thanks

**Comment by Duaner** [comment]
Hello guys,

We are working on a new version of the toolbar that fixes this issue. 
We are deploying it progressively and can start giving you access to it. You can ask that on the support. 

Renaud

**Comment by uglow** [comment]
Is it possible to also use a newer version of jquery (if you need to use it at all)?

**Comment by kevinboudot** [comment]
Thanks Renaud ! 🙏

**Comment by Duaner** [comment]
@uglow We completely removed JQuery on the new version ;)

**Comment by arnaudlewis** [comment]
It's fixed in the new version and it's currently deployed to all of our users.
Ask the team if you don't have access yet and we can activate it for you.
