### ISSUE TITLE
Script brouillon

### ISSUE THREAD

**Issue by JrmPrcht** [prismicio/prismic-toolbar#56]
After trying to integrate the script provided by Prismic to manage the "Preview" mode, we encounter problems displaying the site. 

Here is the error that occurred when integrating the script :
<img width="261" alt="image 1" src="https://user-images.githubusercontent.com/59874539/72348052-cb030f80-36d9-11ea-958c-f9eb414cbdd1.png">

After having followed Prismic's recommendations, here is the script we get : 
<img width="530" alt="image 2" src="https://user-images.githubusercontent.com/59874539/72348067-d35b4a80-36d9-11ea-8f66-40a51fe2da92.png">

The modified script doesn't seem to have a console error, but it contains corrupted style elements (injected in the dom) which lead to these important display problems : cf screenshot ("image 3") of the inspector for an example of injected style)
![image 3](https://user-images.githubusercontent.com/59874539/72348074-d7876800-36d9-11ea-9351-31fdadb8d247.png)

Thank you.

**Comment by Duaner** [comment]
Hello @JrmPrcht ,

Could you send us a screenshot on how the toolbar is impacting your website style ? 

Thanks,
Renaud

**Comment by JrmPrcht** [comment]
Hello Renaud,

The script error adds in particular a big empty space below the footer :
<img width="2048" alt="Capture d’écran 2019-12-17 à 14 46 14" src="https://user-images.githubusercontent.com/59874539/72350154-2c2ce200-36de-11ea-86db-d3cbcb62cdee.png">

Thanks,
Jérémy
