### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by tremby** [prismicio/prismic-toolbar#9]
I know there are some docs here https://prismic.io/docs/javascript/beyond-the-api/in-website-preview but that looks to be for an older version. It requires Jquery (while this one doesn't seem to), for example.

I don't know how to use this. The "How to use it?" section of the readme says only how to install it.

My app is totally client-side, in React.

- Do I use npm-prismic-toolbar.js or script-prismic-toolbar.js?
- Can I have previews and edit buttons working without a server-side component?
- How do I configure and invoke it?
- Can I lazy-load and invoke it only when needed? Obviously I can do that on a /preview route, but what about the edit button? How do I tell when a Prismic user is present?

**Comment by tremby** [comment]
Found the docs: https://prismic.io/docs/reactjs/beyond-the-api/in-website-preview

Please add links to the documentation to the readme. And probably also update the documentation I linked originally above, if that's indeed out of date.

I suppose the answer to my last question there, about detecting presence of a Prismic user and lazy-loading the script if necessary, is that I can't know whether there's a Prismic user until I've run the toolbar script, so I need to run it at all times. Is that accurate?

**Comment by levimykel** [comment]
Hi @tremby,

I'm glad that you found the docs. Fortunately they should now all be up to date. And you are correct about your last question. You need to run it anyway to know if a Prismic user is viewing the page, so there is not really anyway to lazy-load it.

So hopefully you have everything you need.

I also updated the README to reflect the changes in usage.

Closing this issue.

**Comment by tremby** [comment]
I still think it would be a good idea to add a link from this repository's readme file to https://prismic.io/docs/javascript/beyond-the-api/in-website-preview and https://prismic.io/docs/reactjs/beyond-the-api/in-website-preview and any other relevant resources.

**Comment by levimykel** [comment]
Good point, I added a link to the docs as well. Thanks.
